name: Maven Library Snapshot

on:
  push:
    branches:
      - main
      - LTS/*
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/maven-lib-snapshot.yml@main
    with:
      private: false
      product-key: command-line-arguments
      product-repo: zepben/command-line-arguments
    secrets: inherit
